Permit syncusers on plain mysql-server
percona/proxysql-admin-tool pull request #156
Opened 2019-05-10 08:25 UTC by amon-ra

This patch adds the posibility to sync users in a plain mysql server, It is a minimal patch that permits the use of the script without galera tables.

Use with: CLUSTER_HOSTNAME=mysql-server WRITER_NODE=mysql-server:3306 in config file

2019-08-15 07:43 UTC, john9x commented
Hi!
We are very need this. Please merge!

2019-10-21 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/proxysql-admin-tool?pullRequest=156) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/percona/proxysql-admin-tool?pullRequest=156) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/proxysql-admin-tool?pullRequest=156) it.</sub>

2019-11-14 00:07 UTC, kennt-percona requested changes
There are some issues with this PR:
(1) This changes the default behavior.  So for users with a cluster, this will always use the WRITE_NODE (which may be offline), rather than a cluster node.  Plus, it skips the check if the WRITE_NODE is the CLUSTER_HOSTNAME.
Another way to skip the cluster check would be to use '--force' with  '--syncusers'. In this case, it would mean that we use the CLUSTER_HOSTNAME without checking the cluster status.
(2) Also needs to add a test
(3) Documentation (readme + help text)

2021-09-15 12:31 UTC, kennt-percona commented
This is being fixed in:
https://github.com/percona/proxysql-admin-tool/pull/211

A standalone MySQL node can be synced by using the --server option with --syncusers or --sync-multi-cluster-users.

2021-09-15 12:31 UTC, closed without merging