PSQLADM-157 - Check for file existing & readable before trying to cat it
percona/proxysql-admin-tool pull request #176
Opened 2019-10-09 15:50 UTC by altmannmarcelo

Adjusted the tool to test if file exists before trying to cat it.

2019-10-16 04:21 UTC, kennt-percona requested changes

2019-10-16 04:21 UTC, kennt-percona commented on proxysql-status
> +      if [[ -f "/var/lib/proxysql/host_priority.conf" ]]; then
This only checks for existence, do you also want to check for readability (should use -r)?  Also, can you merge the commit into the v2.0.7-dev branch.

2019-10-17 09:38 UTC, altmannmarcelo commented
@kennt-percona ready for next review

2019-10-18 01:18 UTC, merged

2019-10-18 01:18 UTC, kennt-percona commented
LGTM