PSQLADM-327 : proxysql-admin --syncusers does not work for async repl…
percona/proxysql-admin-tool pull request #211
Opened 2021-09-15 06:28 UTC by kennt-percona

…ication

Issue
Running --syncusers or --sync-multi-cluster-users does not work if
the node being synced is not a cluster node.  The code checks to
see if the node is part of the cluster and errors out otherwise.

Solution
Added the --server option. If this is specified with --syncusers or
--sync-multi-cluster-users, then the check for cluster membership
is skipped, thus allowing standalone nodes to be synced.

2021-10-18 16:05 UTC, altmannmarcelo requested changes
Can you add a new check to make sure that when --server is passed the user also passes --syncusers and --sync-multi-cluster-users

2021-10-18 16:06 UTC, altmannmarcelo commented on proxysql-admin
>                         "\n-- Please check the PXC connection parameters and status."
```suggestion
                       "\n-- Please check the server connection parameters and status."
```

2021-10-18 16:06 UTC, altmannmarcelo commented on proxysql-admin
>                         "\n-- Please check the PXC connection parameters and status."
```suggestion
                       "\n-- Please check the server connection parameters and status."
```

2021-10-18 16:07 UTC, altmannmarcelo commented on proxysql-admin
> +    echo -e "\nSyncing user accounts from PXC to ProxySQL"
```suggestion
    echo -e "\nSyncing user accounts from PXC(${CLUSTER_HOSTNAME}:${CLUSTER_PORT}) to ProxySQL"
```

2021-10-22 12:35 UTC, kennt-percona commented on proxysql-admin
>                         "\n-- Please check the PXC connection parameters and status."
fixed

2021-10-22 12:36 UTC, kennt-percona commented on proxysql-admin
>                         "\n-- Please check the PXC connection parameters and status."
fixed

2021-10-22 12:36 UTC, kennt-percona commented on proxysql-admin
> +    echo -e "\nSyncing user accounts from PXC to ProxySQL"
fixed

2021-10-23 06:18 UTC, kennt-percona commented
Added a check to ensure that --server only works for --syncusers and --sync-multi-cluster-users

2021-10-28 12:07 UTC, altmannmarcelo approved these changes
LGTM

2021-10-29 06:45 UTC, merged